TrajectoryPlannerROS:
  max_vel_x: 5
  min_vel_x: 0.1
  max_vel_theta: 10
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false
  yaw_goal_tolerance: 0.1 # about 6 degrees
  xy_goal_tolerance: 0.1 # 10 cm
