obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, 0.0], [0.3, -0.3]]
footprint_padding: 0.01

max_obstacle_height: 1.0
min_obstacle_height: 0.0
observation_sources: point_cloud_sensor
point_cloud_sensor: {data_type: PointCloud2, topic: /sensor/velodyne, marking: true, clearing: true}
